Kind: Deployment
apiVersion: apps/v1
metadata: 
  name: frontend-deployment
  namespace: wanderlust
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: wanderlust
  template:
    metadata:
      labels:
        app: wanderlust
    spec:
      containers:
      - name: wanderlust-app
        image: umerfarooqsyed/mern-devsecops-project:latestImageVersion
        ports:
        - containerPort: 5173

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: wanderlust
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000


